bot:
  name: ${BOT_NAME:OSurMoviesBot}
  key: ${BOT_KEY:token}

spring:
  application:
    name: bot
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/o_sur_movies_bot}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/liquibase/liquibase-changeLog.xml

logging:
  file: ${LOG_FILE:logs/bot.log}
  max-size: ${LOG_MAX_SIZE:10MB}
  max-history: ${LOG_MAX_HISTORY:10}
  level:
    root: INFO
